// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldBirthday holds the string denoting the birthday field in the database.
	FieldBirthday = "birthday"
	// FieldTel holds the string denoting the tel field in the database.
	FieldTel = "tel"

	// EdgeUserConfirmation holds the string denoting the userconfirmation edge name in mutations.
	EdgeUserConfirmation = "UserConfirmation"

	// Table holds the table name of the user in the database.
	Table = "users"
	// UserConfirmationTable is the table the holds the UserConfirmation relation/edge.
	UserConfirmationTable = "confirmations"
	// UserConfirmationInverseTable is the table name for the Confirmation entity.
	// It exists in this package in order to avoid circular dependency with the "confirmation" package.
	UserConfirmationInverseTable = "confirmations"
	// UserConfirmationColumn is the table column denoting the UserConfirmation relation/edge.
	UserConfirmationColumn = "user_user_confirmation"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPassword,
	FieldBirthday,
	FieldTel,
}
