// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Borrow is the predicate function for borrow builders.
type Borrow func(*sql.Selector)

// Confirmation is the predicate function for confirmation builders.
type Confirmation func(*sql.Selector)

// Stadium is the predicate function for stadium builders.
type Stadium func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
