// Code generated by entc, DO NOT EDIT.

package borrow

const (
	// Label holds the string label denoting the borrow type in the database.
	Label = "borrow"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"

	// EdgeBorrowConfirmation holds the string denoting the borrowconfirmation edge name in mutations.
	EdgeBorrowConfirmation = "BorrowConfirmation"

	// Table holds the table name of the borrow in the database.
	Table = "borrows"
	// BorrowConfirmationTable is the table the holds the BorrowConfirmation relation/edge.
	BorrowConfirmationTable = "confirmations"
	// BorrowConfirmationInverseTable is the table name for the Confirmation entity.
	// It exists in this package in order to avoid circular dependency with the "confirmation" package.
	BorrowConfirmationInverseTable = "confirmations"
	// BorrowConfirmationColumn is the table column denoting the BorrowConfirmation relation/edge.
	BorrowConfirmationColumn = "borrow_borrow_confirmation"
)

// Columns holds all SQL columns for borrow fields.
var Columns = []string{
	FieldID,
	FieldType,
}

var (
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
)
