// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/tew147258/app/ent/borrow"
	"github.com/tew147258/app/ent/confirmation"
)

// BorrowCreate is the builder for creating a Borrow entity.
type BorrowCreate struct {
	config
	mutation *BorrowMutation
	hooks    []Hook
}

// SetType sets the type field.
func (bc *BorrowCreate) SetType(s string) *BorrowCreate {
	bc.mutation.SetType(s)
	return bc
}

// AddBorrowConfirmationIDs adds the BorrowConfirmation edge to Confirmation by ids.
func (bc *BorrowCreate) AddBorrowConfirmationIDs(ids ...int) *BorrowCreate {
	bc.mutation.AddBorrowConfirmationIDs(ids...)
	return bc
}

// AddBorrowConfirmation adds the BorrowConfirmation edges to Confirmation.
func (bc *BorrowCreate) AddBorrowConfirmation(c ...*Confirmation) *BorrowCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return bc.AddBorrowConfirmationIDs(ids...)
}

// Mutation returns the BorrowMutation object of the builder.
func (bc *BorrowCreate) Mutation() *BorrowMutation {
	return bc.mutation
}

// Save creates the Borrow in the database.
func (bc *BorrowCreate) Save(ctx context.Context) (*Borrow, error) {
	if _, ok := bc.mutation.GetType(); !ok {
		return nil, &ValidationError{Name: "type", err: errors.New("ent: missing required field \"type\"")}
	}
	if v, ok := bc.mutation.GetType(); ok {
		if err := borrow.TypeValidator(v); err != nil {
			return nil, &ValidationError{Name: "type", err: fmt.Errorf("ent: validator failed for field \"type\": %w", err)}
		}
	}
	var (
		err  error
		node *Borrow
	)
	if len(bc.hooks) == 0 {
		node, err = bc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BorrowMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bc.mutation = mutation
			node, err = bc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(bc.hooks) - 1; i >= 0; i-- {
			mut = bc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BorrowCreate) SaveX(ctx context.Context) *Borrow {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bc *BorrowCreate) sqlSave(ctx context.Context) (*Borrow, error) {
	b, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	b.ID = int(id)
	return b, nil
}

func (bc *BorrowCreate) createSpec() (*Borrow, *sqlgraph.CreateSpec) {
	var (
		b     = &Borrow{config: bc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: borrow.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: borrow.FieldID,
			},
		}
	)
	if value, ok := bc.mutation.GetType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: borrow.FieldType,
		})
		b.Type = value
	}
	if nodes := bc.mutation.BorrowConfirmationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   borrow.BorrowConfirmationTable,
			Columns: []string{borrow.BorrowConfirmationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: confirmation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return b, _spec
}
