// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/tew147258/app/ent/borrow"
	"github.com/tew147258/app/ent/confirmation"
	"github.com/tew147258/app/ent/predicate"
	"github.com/tew147258/app/ent/stadium"
	"github.com/tew147258/app/ent/user"
)

// ConfirmationUpdate is the builder for updating Confirmation entities.
type ConfirmationUpdate struct {
	config
	hooks      []Hook
	mutation   *ConfirmationMutation
	predicates []predicate.Confirmation
}

// Where adds a new predicate for the builder.
func (cu *ConfirmationUpdate) Where(ps ...predicate.Confirmation) *ConfirmationUpdate {
	cu.predicates = append(cu.predicates, ps...)
	return cu
}

// SetBookingdate sets the bookingdate field.
func (cu *ConfirmationUpdate) SetBookingdate(t time.Time) *ConfirmationUpdate {
	cu.mutation.SetBookingdate(t)
	return cu
}

// SetBookingstart sets the bookingstart field.
func (cu *ConfirmationUpdate) SetBookingstart(t time.Time) *ConfirmationUpdate {
	cu.mutation.SetBookingstart(t)
	return cu
}

// SetBookingend sets the bookingend field.
func (cu *ConfirmationUpdate) SetBookingend(t time.Time) *ConfirmationUpdate {
	cu.mutation.SetBookingend(t)
	return cu
}

// SetHourstime sets the hourstime field.
func (cu *ConfirmationUpdate) SetHourstime(i int) *ConfirmationUpdate {
	cu.mutation.ResetHourstime()
	cu.mutation.SetHourstime(i)
	return cu
}

// AddHourstime adds i to hourstime.
func (cu *ConfirmationUpdate) AddHourstime(i int) *ConfirmationUpdate {
	cu.mutation.AddHourstime(i)
	return cu
}

// SetConfirmationUserID sets the ConfirmationUser edge to User by id.
func (cu *ConfirmationUpdate) SetConfirmationUserID(id int) *ConfirmationUpdate {
	cu.mutation.SetConfirmationUserID(id)
	return cu
}

// SetNillableConfirmationUserID sets the ConfirmationUser edge to User by id if the given value is not nil.
func (cu *ConfirmationUpdate) SetNillableConfirmationUserID(id *int) *ConfirmationUpdate {
	if id != nil {
		cu = cu.SetConfirmationUserID(*id)
	}
	return cu
}

// SetConfirmationUser sets the ConfirmationUser edge to User.
func (cu *ConfirmationUpdate) SetConfirmationUser(u *User) *ConfirmationUpdate {
	return cu.SetConfirmationUserID(u.ID)
}

// SetConfirmationStadiumID sets the ConfirmationStadium edge to Stadium by id.
func (cu *ConfirmationUpdate) SetConfirmationStadiumID(id int) *ConfirmationUpdate {
	cu.mutation.SetConfirmationStadiumID(id)
	return cu
}

// SetNillableConfirmationStadiumID sets the ConfirmationStadium edge to Stadium by id if the given value is not nil.
func (cu *ConfirmationUpdate) SetNillableConfirmationStadiumID(id *int) *ConfirmationUpdate {
	if id != nil {
		cu = cu.SetConfirmationStadiumID(*id)
	}
	return cu
}

// SetConfirmationStadium sets the ConfirmationStadium edge to Stadium.
func (cu *ConfirmationUpdate) SetConfirmationStadium(s *Stadium) *ConfirmationUpdate {
	return cu.SetConfirmationStadiumID(s.ID)
}

// SetConfirmationBorrowID sets the ConfirmationBorrow edge to Borrow by id.
func (cu *ConfirmationUpdate) SetConfirmationBorrowID(id int) *ConfirmationUpdate {
	cu.mutation.SetConfirmationBorrowID(id)
	return cu
}

// SetNillableConfirmationBorrowID sets the ConfirmationBorrow edge to Borrow by id if the given value is not nil.
func (cu *ConfirmationUpdate) SetNillableConfirmationBorrowID(id *int) *ConfirmationUpdate {
	if id != nil {
		cu = cu.SetConfirmationBorrowID(*id)
	}
	return cu
}

// SetConfirmationBorrow sets the ConfirmationBorrow edge to Borrow.
func (cu *ConfirmationUpdate) SetConfirmationBorrow(b *Borrow) *ConfirmationUpdate {
	return cu.SetConfirmationBorrowID(b.ID)
}

// Mutation returns the ConfirmationMutation object of the builder.
func (cu *ConfirmationUpdate) Mutation() *ConfirmationMutation {
	return cu.mutation
}

// ClearConfirmationUser clears the ConfirmationUser edge to User.
func (cu *ConfirmationUpdate) ClearConfirmationUser() *ConfirmationUpdate {
	cu.mutation.ClearConfirmationUser()
	return cu
}

// ClearConfirmationStadium clears the ConfirmationStadium edge to Stadium.
func (cu *ConfirmationUpdate) ClearConfirmationStadium() *ConfirmationUpdate {
	cu.mutation.ClearConfirmationStadium()
	return cu
}

// ClearConfirmationBorrow clears the ConfirmationBorrow edge to Borrow.
func (cu *ConfirmationUpdate) ClearConfirmationBorrow() *ConfirmationUpdate {
	cu.mutation.ClearConfirmationBorrow()
	return cu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (cu *ConfirmationUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ConfirmationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ConfirmationUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ConfirmationUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ConfirmationUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *ConfirmationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   confirmation.Table,
			Columns: confirmation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: confirmation.FieldID,
			},
		},
	}
	if ps := cu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Bookingdate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: confirmation.FieldBookingdate,
		})
	}
	if value, ok := cu.mutation.Bookingstart(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: confirmation.FieldBookingstart,
		})
	}
	if value, ok := cu.mutation.Bookingend(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: confirmation.FieldBookingend,
		})
	}
	if value, ok := cu.mutation.Hourstime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: confirmation.FieldHourstime,
		})
	}
	if value, ok := cu.mutation.AddedHourstime(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: confirmation.FieldHourstime,
		})
	}
	if cu.mutation.ConfirmationUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmation.ConfirmationUserTable,
			Columns: []string{confirmation.ConfirmationUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ConfirmationUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmation.ConfirmationUserTable,
			Columns: []string{confirmation.ConfirmationUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.ConfirmationStadiumCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmation.ConfirmationStadiumTable,
			Columns: []string{confirmation.ConfirmationStadiumColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: stadium.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ConfirmationStadiumIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmation.ConfirmationStadiumTable,
			Columns: []string{confirmation.ConfirmationStadiumColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: stadium.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.ConfirmationBorrowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmation.ConfirmationBorrowTable,
			Columns: []string{confirmation.ConfirmationBorrowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: borrow.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ConfirmationBorrowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmation.ConfirmationBorrowTable,
			Columns: []string{confirmation.ConfirmationBorrowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: borrow.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{confirmation.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ConfirmationUpdateOne is the builder for updating a single Confirmation entity.
type ConfirmationUpdateOne struct {
	config
	hooks    []Hook
	mutation *ConfirmationMutation
}

// SetBookingdate sets the bookingdate field.
func (cuo *ConfirmationUpdateOne) SetBookingdate(t time.Time) *ConfirmationUpdateOne {
	cuo.mutation.SetBookingdate(t)
	return cuo
}

// SetBookingstart sets the bookingstart field.
func (cuo *ConfirmationUpdateOne) SetBookingstart(t time.Time) *ConfirmationUpdateOne {
	cuo.mutation.SetBookingstart(t)
	return cuo
}

// SetBookingend sets the bookingend field.
func (cuo *ConfirmationUpdateOne) SetBookingend(t time.Time) *ConfirmationUpdateOne {
	cuo.mutation.SetBookingend(t)
	return cuo
}

// SetHourstime sets the hourstime field.
func (cuo *ConfirmationUpdateOne) SetHourstime(i int) *ConfirmationUpdateOne {
	cuo.mutation.ResetHourstime()
	cuo.mutation.SetHourstime(i)
	return cuo
}

// AddHourstime adds i to hourstime.
func (cuo *ConfirmationUpdateOne) AddHourstime(i int) *ConfirmationUpdateOne {
	cuo.mutation.AddHourstime(i)
	return cuo
}

// SetConfirmationUserID sets the ConfirmationUser edge to User by id.
func (cuo *ConfirmationUpdateOne) SetConfirmationUserID(id int) *ConfirmationUpdateOne {
	cuo.mutation.SetConfirmationUserID(id)
	return cuo
}

// SetNillableConfirmationUserID sets the ConfirmationUser edge to User by id if the given value is not nil.
func (cuo *ConfirmationUpdateOne) SetNillableConfirmationUserID(id *int) *ConfirmationUpdateOne {
	if id != nil {
		cuo = cuo.SetConfirmationUserID(*id)
	}
	return cuo
}

// SetConfirmationUser sets the ConfirmationUser edge to User.
func (cuo *ConfirmationUpdateOne) SetConfirmationUser(u *User) *ConfirmationUpdateOne {
	return cuo.SetConfirmationUserID(u.ID)
}

// SetConfirmationStadiumID sets the ConfirmationStadium edge to Stadium by id.
func (cuo *ConfirmationUpdateOne) SetConfirmationStadiumID(id int) *ConfirmationUpdateOne {
	cuo.mutation.SetConfirmationStadiumID(id)
	return cuo
}

// SetNillableConfirmationStadiumID sets the ConfirmationStadium edge to Stadium by id if the given value is not nil.
func (cuo *ConfirmationUpdateOne) SetNillableConfirmationStadiumID(id *int) *ConfirmationUpdateOne {
	if id != nil {
		cuo = cuo.SetConfirmationStadiumID(*id)
	}
	return cuo
}

// SetConfirmationStadium sets the ConfirmationStadium edge to Stadium.
func (cuo *ConfirmationUpdateOne) SetConfirmationStadium(s *Stadium) *ConfirmationUpdateOne {
	return cuo.SetConfirmationStadiumID(s.ID)
}

// SetConfirmationBorrowID sets the ConfirmationBorrow edge to Borrow by id.
func (cuo *ConfirmationUpdateOne) SetConfirmationBorrowID(id int) *ConfirmationUpdateOne {
	cuo.mutation.SetConfirmationBorrowID(id)
	return cuo
}

// SetNillableConfirmationBorrowID sets the ConfirmationBorrow edge to Borrow by id if the given value is not nil.
func (cuo *ConfirmationUpdateOne) SetNillableConfirmationBorrowID(id *int) *ConfirmationUpdateOne {
	if id != nil {
		cuo = cuo.SetConfirmationBorrowID(*id)
	}
	return cuo
}

// SetConfirmationBorrow sets the ConfirmationBorrow edge to Borrow.
func (cuo *ConfirmationUpdateOne) SetConfirmationBorrow(b *Borrow) *ConfirmationUpdateOne {
	return cuo.SetConfirmationBorrowID(b.ID)
}

// Mutation returns the ConfirmationMutation object of the builder.
func (cuo *ConfirmationUpdateOne) Mutation() *ConfirmationMutation {
	return cuo.mutation
}

// ClearConfirmationUser clears the ConfirmationUser edge to User.
func (cuo *ConfirmationUpdateOne) ClearConfirmationUser() *ConfirmationUpdateOne {
	cuo.mutation.ClearConfirmationUser()
	return cuo
}

// ClearConfirmationStadium clears the ConfirmationStadium edge to Stadium.
func (cuo *ConfirmationUpdateOne) ClearConfirmationStadium() *ConfirmationUpdateOne {
	cuo.mutation.ClearConfirmationStadium()
	return cuo
}

// ClearConfirmationBorrow clears the ConfirmationBorrow edge to Borrow.
func (cuo *ConfirmationUpdateOne) ClearConfirmationBorrow() *ConfirmationUpdateOne {
	cuo.mutation.ClearConfirmationBorrow()
	return cuo
}

// Save executes the query and returns the updated entity.
func (cuo *ConfirmationUpdateOne) Save(ctx context.Context) (*Confirmation, error) {

	var (
		err  error
		node *Confirmation
	)
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ConfirmationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ConfirmationUpdateOne) SaveX(ctx context.Context) *Confirmation {
	c, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return c
}

// Exec executes the query on the entity.
func (cuo *ConfirmationUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ConfirmationUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *ConfirmationUpdateOne) sqlSave(ctx context.Context) (c *Confirmation, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   confirmation.Table,
			Columns: confirmation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: confirmation.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Confirmation.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := cuo.mutation.Bookingdate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: confirmation.FieldBookingdate,
		})
	}
	if value, ok := cuo.mutation.Bookingstart(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: confirmation.FieldBookingstart,
		})
	}
	if value, ok := cuo.mutation.Bookingend(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: confirmation.FieldBookingend,
		})
	}
	if value, ok := cuo.mutation.Hourstime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: confirmation.FieldHourstime,
		})
	}
	if value, ok := cuo.mutation.AddedHourstime(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: confirmation.FieldHourstime,
		})
	}
	if cuo.mutation.ConfirmationUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmation.ConfirmationUserTable,
			Columns: []string{confirmation.ConfirmationUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ConfirmationUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmation.ConfirmationUserTable,
			Columns: []string{confirmation.ConfirmationUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.ConfirmationStadiumCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmation.ConfirmationStadiumTable,
			Columns: []string{confirmation.ConfirmationStadiumColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: stadium.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ConfirmationStadiumIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmation.ConfirmationStadiumTable,
			Columns: []string{confirmation.ConfirmationStadiumColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: stadium.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.ConfirmationBorrowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmation.ConfirmationBorrowTable,
			Columns: []string{confirmation.ConfirmationBorrowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: borrow.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ConfirmationBorrowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   confirmation.ConfirmationBorrowTable,
			Columns: []string{confirmation.ConfirmationBorrowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: borrow.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	c = &Confirmation{config: cuo.config}
	_spec.Assign = c.assignValues
	_spec.ScanValues = c.scanValues()
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{confirmation.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return c, nil
}
