// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/tew147258/app/ent/borrow"
	"github.com/tew147258/app/ent/schema"
	"github.com/tew147258/app/ent/stadium"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	borrowFields := schema.Borrow{}.Fields()
	_ = borrowFields
	// borrowDescType is the schema descriptor for type field.
	borrowDescType := borrowFields[0].Descriptor()
	// borrow.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	borrow.TypeValidator = borrowDescType.Validators[0].(func(string) error)
	stadiumFields := schema.Stadium{}.Fields()
	_ = stadiumFields
	// stadiumDescNamestadium is the schema descriptor for namestadium field.
	stadiumDescNamestadium := stadiumFields[0].Descriptor()
	// stadium.NamestadiumValidator is a validator for the "namestadium" field. It is called by the builders before save.
	stadium.NamestadiumValidator = stadiumDescNamestadium.Validators[0].(func(string) error)
}
