// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/tew147258/app/ent/confirmation"
	"github.com/tew147258/app/ent/stadium"
)

// StadiumCreate is the builder for creating a Stadium entity.
type StadiumCreate struct {
	config
	mutation *StadiumMutation
	hooks    []Hook
}

// SetNamestadium sets the namestadium field.
func (sc *StadiumCreate) SetNamestadium(s string) *StadiumCreate {
	sc.mutation.SetNamestadium(s)
	return sc
}

// AddStadiumConfirmationIDs adds the StadiumConfirmation edge to Confirmation by ids.
func (sc *StadiumCreate) AddStadiumConfirmationIDs(ids ...int) *StadiumCreate {
	sc.mutation.AddStadiumConfirmationIDs(ids...)
	return sc
}

// AddStadiumConfirmation adds the StadiumConfirmation edges to Confirmation.
func (sc *StadiumCreate) AddStadiumConfirmation(c ...*Confirmation) *StadiumCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return sc.AddStadiumConfirmationIDs(ids...)
}

// Mutation returns the StadiumMutation object of the builder.
func (sc *StadiumCreate) Mutation() *StadiumMutation {
	return sc.mutation
}

// Save creates the Stadium in the database.
func (sc *StadiumCreate) Save(ctx context.Context) (*Stadium, error) {
	if _, ok := sc.mutation.Namestadium(); !ok {
		return nil, &ValidationError{Name: "namestadium", err: errors.New("ent: missing required field \"namestadium\"")}
	}
	if v, ok := sc.mutation.Namestadium(); ok {
		if err := stadium.NamestadiumValidator(v); err != nil {
			return nil, &ValidationError{Name: "namestadium", err: fmt.Errorf("ent: validator failed for field \"namestadium\": %w", err)}
		}
	}
	var (
		err  error
		node *Stadium
	)
	if len(sc.hooks) == 0 {
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StadiumMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StadiumCreate) SaveX(ctx context.Context) *Stadium {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sc *StadiumCreate) sqlSave(ctx context.Context) (*Stadium, error) {
	s, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}

func (sc *StadiumCreate) createSpec() (*Stadium, *sqlgraph.CreateSpec) {
	var (
		s     = &Stadium{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: stadium.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: stadium.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.Namestadium(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: stadium.FieldNamestadium,
		})
		s.Namestadium = value
	}
	if nodes := sc.mutation.StadiumConfirmationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stadium.StadiumConfirmationTable,
			Columns: []string{stadium.StadiumConfirmationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: confirmation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return s, _spec
}
