// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/tew147258/app/ent/stadium"
)

// Stadium is the model entity for the Stadium schema.
type Stadium struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Namestadium holds the value of the "namestadium" field.
	Namestadium string `json:"namestadium,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StadiumQuery when eager-loading is set.
	Edges StadiumEdges `json:"edges"`
}

// StadiumEdges holds the relations/edges for other nodes in the graph.
type StadiumEdges struct {
	// StadiumConfirmation holds the value of the StadiumConfirmation edge.
	StadiumConfirmation []*Confirmation
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// StadiumConfirmationOrErr returns the StadiumConfirmation value or an error if the edge
// was not loaded in eager-loading.
func (e StadiumEdges) StadiumConfirmationOrErr() ([]*Confirmation, error) {
	if e.loadedTypes[0] {
		return e.StadiumConfirmation, nil
	}
	return nil, &NotLoadedError{edge: "StadiumConfirmation"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Stadium) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // namestadium
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Stadium fields.
func (s *Stadium) assignValues(values ...interface{}) error {
	if m, n := len(values), len(stadium.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	s.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field namestadium", values[0])
	} else if value.Valid {
		s.Namestadium = value.String
	}
	return nil
}

// QueryStadiumConfirmation queries the StadiumConfirmation edge of the Stadium.
func (s *Stadium) QueryStadiumConfirmation() *ConfirmationQuery {
	return (&StadiumClient{config: s.config}).QueryStadiumConfirmation(s)
}

// Update returns a builder for updating this Stadium.
// Note that, you need to call Stadium.Unwrap() before calling this method, if this Stadium
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Stadium) Update() *StadiumUpdateOne {
	return (&StadiumClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (s *Stadium) Unwrap() *Stadium {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Stadium is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Stadium) String() string {
	var builder strings.Builder
	builder.WriteString("Stadium(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", namestadium=")
	builder.WriteString(s.Namestadium)
	builder.WriteByte(')')
	return builder.String()
}

// Stadia is a parsable slice of Stadium.
type Stadia []*Stadium

func (s Stadia) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
