// Code generated by entc, DO NOT EDIT.

package confirmation

const (
	// Label holds the string label denoting the confirmation type in the database.
	Label = "confirmation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBookingdate holds the string denoting the bookingdate field in the database.
	FieldBookingdate = "bookingdate"
	// FieldBookingstart holds the string denoting the bookingstart field in the database.
	FieldBookingstart = "bookingstart"
	// FieldBookingend holds the string denoting the bookingend field in the database.
	FieldBookingend = "bookingend"
	// FieldHourstime holds the string denoting the hourstime field in the database.
	FieldHourstime = "hourstime"

	// EdgeConfirmationUser holds the string denoting the confirmationuser edge name in mutations.
	EdgeConfirmationUser = "ConfirmationUser"
	// EdgeConfirmationStadium holds the string denoting the confirmationstadium edge name in mutations.
	EdgeConfirmationStadium = "ConfirmationStadium"
	// EdgeConfirmationBorrow holds the string denoting the confirmationborrow edge name in mutations.
	EdgeConfirmationBorrow = "ConfirmationBorrow"

	// Table holds the table name of the confirmation in the database.
	Table = "confirmations"
	// ConfirmationUserTable is the table the holds the ConfirmationUser relation/edge.
	ConfirmationUserTable = "confirmations"
	// ConfirmationUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ConfirmationUserInverseTable = "users"
	// ConfirmationUserColumn is the table column denoting the ConfirmationUser relation/edge.
	ConfirmationUserColumn = "user_user_confirmation"
	// ConfirmationStadiumTable is the table the holds the ConfirmationStadium relation/edge.
	ConfirmationStadiumTable = "confirmations"
	// ConfirmationStadiumInverseTable is the table name for the Stadium entity.
	// It exists in this package in order to avoid circular dependency with the "stadium" package.
	ConfirmationStadiumInverseTable = "stadia"
	// ConfirmationStadiumColumn is the table column denoting the ConfirmationStadium relation/edge.
	ConfirmationStadiumColumn = "stadium_stadium_confirmation"
	// ConfirmationBorrowTable is the table the holds the ConfirmationBorrow relation/edge.
	ConfirmationBorrowTable = "confirmations"
	// ConfirmationBorrowInverseTable is the table name for the Borrow entity.
	// It exists in this package in order to avoid circular dependency with the "borrow" package.
	ConfirmationBorrowInverseTable = "borrows"
	// ConfirmationBorrowColumn is the table column denoting the ConfirmationBorrow relation/edge.
	ConfirmationBorrowColumn = "borrow_borrow_confirmation"
)

// Columns holds all SQL columns for confirmation fields.
var Columns = []string{
	FieldID,
	FieldBookingdate,
	FieldBookingstart,
	FieldBookingend,
	FieldHourstime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Confirmation type.
var ForeignKeys = []string{
	"borrow_borrow_confirmation",
	"stadium_stadium_confirmation",
	"user_user_confirmation",
}
