/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntConfirmation,
    EntConfirmationFromJSON,
    EntConfirmationFromJSONTyped,
    EntConfirmationToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBorrowEdges
 */
export interface EntBorrowEdges {
    /**
     * BorrowConfirmation holds the value of the BorrowConfirmation edge.
     * @type {Array<EntConfirmation>}
     * @memberof EntBorrowEdges
     */
    borrowConfirmation?: Array<EntConfirmation>;
}

export function EntBorrowEdgesFromJSON(json: any): EntBorrowEdges {
    return EntBorrowEdgesFromJSONTyped(json, false);
}

export function EntBorrowEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBorrowEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'borrowConfirmation': !exists(json, 'borrowConfirmation') ? undefined : ((json['borrowConfirmation'] as Array<any>).map(EntConfirmationFromJSON)),
    };
}

export function EntBorrowEdgesToJSON(value?: EntBorrowEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'borrowConfirmation': value.borrowConfirmation === undefined ? undefined : ((value.borrowConfirmation as Array<any>).map(EntConfirmationToJSON)),
    };
}


