/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBorrow,
    EntBorrowFromJSON,
    EntBorrowFromJSONTyped,
    EntBorrowToJSON,
    EntStadium,
    EntStadiumFromJSON,
    EntStadiumFromJSONTyped,
    EntStadiumToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntConfirmationEdges
 */
export interface EntConfirmationEdges {
    /**
     * 
     * @type {EntBorrow}
     * @memberof EntConfirmationEdges
     */
    confirmationBorrow?: EntBorrow;
    /**
     * 
     * @type {EntStadium}
     * @memberof EntConfirmationEdges
     */
    confirmationStadium?: EntStadium;
    /**
     * 
     * @type {EntUser}
     * @memberof EntConfirmationEdges
     */
    confirmationUser?: EntUser;
}

export function EntConfirmationEdgesFromJSON(json: any): EntConfirmationEdges {
    return EntConfirmationEdgesFromJSONTyped(json, false);
}

export function EntConfirmationEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntConfirmationEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'confirmationBorrow': !exists(json, 'ConfirmationBorrow') ? undefined : EntBorrowFromJSON(json['ConfirmationBorrow']),
        'confirmationStadium': !exists(json, 'ConfirmationStadium') ? undefined : EntStadiumFromJSON(json['ConfirmationStadium']),
        'confirmationUser': !exists(json, 'ConfirmationUser') ? undefined : EntUserFromJSON(json['ConfirmationUser']),
    };
}

export function EntConfirmationEdgesToJSON(value?: EntConfirmationEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'confirmationBorrow': EntBorrowToJSON(value.confirmationBorrow),
        'confirmationStadium': EntStadiumToJSON(value.confirmationStadium),
        'confirmationUser': EntUserToJSON(value.confirmationUser),
    };
}


