/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntConfirmation,
    EntConfirmationFromJSON,
    EntConfirmationFromJSONTyped,
    EntConfirmationToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntStadiumEdges
 */
export interface EntStadiumEdges {
    /**
     * StadiumConfirmation holds the value of the StadiumConfirmation edge.
     * @type {Array<EntConfirmation>}
     * @memberof EntStadiumEdges
     */
    stadiumConfirmation?: Array<EntConfirmation>;
}

export function EntStadiumEdgesFromJSON(json: any): EntStadiumEdges {
    return EntStadiumEdgesFromJSONTyped(json, false);
}

export function EntStadiumEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntStadiumEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stadiumConfirmation': !exists(json, 'stadiumConfirmation') ? undefined : ((json['stadiumConfirmation'] as Array<any>).map(EntConfirmationFromJSON)),
    };
}

export function EntStadiumEdgesToJSON(value?: EntStadiumEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stadiumConfirmation': value.stadiumConfirmation === undefined ? undefined : ((value.stadiumConfirmation as Array<any>).map(EntConfirmationToJSON)),
    };
}


